<img src="https://miro.medium.com/max/765/1*cyXCE-JcBelTyrK-58w6_Q.png" alt="350" width="400" align="left"/>

# NUMPY LIBRARY TUTORIAL
***By Loris Liusso***



<h2> What is NumPy? </h2>

<ul>

<li>NumPy is a Python library used for working with arrays.</li>

<li>It also has functions for working in domain of linear algebra, fourier transform, and matrices.</li>

<li>NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.</li>

<li>NumPy stands for Numerical Python.</li>
<li>NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.</li>
</ul>

<h2>Why Use NumPy?</h2>
<ul>
<li>In Python we have lists that serve the purpose of arrays, but they are slow to process.</li>

<li>NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.</li>

<li>The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.</li>

<li>Arrays are very frequently used in data science, where speed and resources are very important.</li>
</ul>

## Numpy Ndarray

<img src="https://miro.medium.com/max/831/1*R0wH6D43-rzG7ivvEhSFkA.png" alt="500" width="600" align="left"/>

In [1]:
import numpy as np #import numpy library

In [2]:
arr_1d= np.array([1, 2, 3, 4, 5]) #1d array

arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]) #2d array -> matrix

In [3]:
print(arr_1d)

[1 2 3 4 5]


In [4]:
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**1D Array Operations:**

In [5]:
arr_1d= np.array([1, 2, 3, 4, 5]) #1d array

In [6]:
arr_1d.ndim #1d array -> 1 dimension

1

In [7]:
arr_1d.size #number of elements

5

In [11]:
arr_1d.min()

1

In [12]:
arr_1d.max()

5

In [13]:
arr_1d.sum()

15

In [14]:
np.arange(4) #array with range of numbers [0,4(not included)]

array([0, 1, 2, 3])

In [15]:
np.arange(0,11,2) #stepover

array([ 0,  2,  4,  6,  8, 10])

In [20]:
#Return evenly spaced numbers over a specified interval:

np.linspace(0, 10, 5, dtype=int) #(stop number included in this case)

array([ 0,  2,  5,  7, 10])

**2D Array Operations (MATRIX):**

In [21]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]) #2d array -> matrix

In [23]:
arr_2d.ndim #2d array (matrix) -> 2 dimensions

2

In [26]:
arr_2d.size #number of elements

12

In [28]:
arr_2d.shape #m rows, n columns (mxn)

(3, 4)

In [30]:
arr_2d.min()

1

In [31]:
arr_2d.max()

12

In [32]:
arr_2d.sum()

78

**Access Items:**

<img src="https://numpy.org/doc/stable/_images/np_matrix_indexing.png" alt="600" width="700" align="left"/>

In [ ]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]) #2d array -> matrix

In [33]:
#First element: first row/column (1)

arr_2d[0,0] # [row index, col index]

1

In [34]:
#Only first row

arr_2d[0, :] # same thing -> arr_2d[0]

array([1, 2, 3, 4])

In [35]:
#Only first column

arr_2d[:,0]

array([1, 5, 9])

**Useful Numpy Functions:**

<img src="https://numpy.org/doc/stable/_images/np_ones_zeros_matrix.png" width="700" align="left"/>

In [36]:
np.zeros(2) #1D  -> float numbers by default

array([0., 0.])

In [37]:
np.zeros(2, dtype=int) #with integer numbers

array([0, 0])

In [39]:
np.zeros((2,2)) #2D MATRIX

array([[0., 0.],
       [0., 0.]])

In [42]:
np.ones(2) #1D

array([1., 1.])

In [43]:
np.ones((2,2)) #2D MATRIX

array([[1., 1.],
       [1., 1.]])

In [46]:
np.random.random(3) #1D -> Return random floats in the half-open interval [0.0, 1.0]

array([0.82951774, 0.56115871, 0.53010628])

In [47]:
np.random.random((3,2)) #2D MATRIX

array([[0.15644961, 0.2991167 ],
       [0.559936  , 0.51628567],
       [0.81173459, 0.38051338]])

<img src="https://www.w3resource.com/w3r_images/numpy-array-eye-function-image-1-b.png" width="200" align="left"/>

In [49]:
np.eye(2) #IDENTITY MATRIX 3x3

array([[1., 0.],
       [0., 1.]])

**Reshape Array (modificare dimensioni): Gives a new shape to an array without changing its data.**

<img src="https://numpy.org/doc/stable/_images/np_reshape.png" width="600" align="left"/>

In [ ]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]) #2D ARRAY 3X4

In [51]:
arr_2d_res = arr_2d.reshape(4,3) #2D ARRAY 4X3
print(arr_2d_res)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Boolean Indexing**:

In [ ]:
arr_1d= np.array([1, 2, 3, 4, 5]) #1d array

In [65]:
print(arr_1d < 3) #RETURN BOOLEAN VALUES

[ True  True False False False]


In [66]:
print(arr_1d[arr_1d < 3]) #FILTER: RETURN ARRAY ELEMENTS THAT MEET THE CONDITION

[1 2]


In [73]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]) #2d array -> matrix

In [74]:
print(arr_2d < 3)

[[ True  True False False]
 [False False False False]
 [False False False False]]


In [75]:
print(arr_2d[arr_2d < 3])

[1 2]


In [80]:
np.where(arr_2d < 4, 1, 0) #if True -> 1 else 0

array([[1, 1, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

**Why are Numpy Array so fast?:**

In [84]:
# 2D ndarray of shape (10000, 10000) with random float in [0, 1] interval. That's 100M numbers!
A = np.random.rand(10000, 10000) #RANDOM RAND: Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1].
a = A.tolist()

In [85]:
%%time
total = 0
for row in a:
    for n in row:
        total += n
round(total, 2)

Wall time: 19.5 s


49997715.57

In [86]:
%%time
round(np.sum(A), 2)

Wall time: 310 ms


49997715.57

**Linear Algebra Operations:**

**1D ARRAY:**

In [88]:
#Array 1D operations

In [89]:
a= np.array([1,2,3])
b= np.array([4,5,6])

In [91]:
a+b #addition

array([5, 7, 9])

In [92]:
a-b #subtraction

array([-3, -3, -3])

In [93]:
a*3 #scalar multiplication

array([3, 6, 9])

In [95]:
#Prodotto scalare:

c= np.array([1,0]) 
d= np.array([0,1]) 

e= np.array([1,2,3])
f= np.array([2,4,6]) #combinazione lineare dell'array e (e*2)

#Dot product (prodotto scalare):

print(np.dot(c,d)) # =0 -> prodotto scalare =0, perpendicolari, angolo = 90°
print(np.dot(e,f)) # prodotto scalare positivo & !=0 -> angolo <90°

0
28


**MATRIX OPERATIONS:**

In [ ]:
#2D MATRIX OPERATIONS

In [96]:
M_1 = np.array([[1, 2],  #square matrix 2x2
                [3, 4]])

#scalar multiplication

M_1 * 10

array([[10, 20],
       [30, 40]])

In [97]:
#ARITHMETIC OPERATIONS ON MATRICES 

M_1 = np.array([[1, 2],  #square matrix 2x2
                [3, 4]])
      
M_2 = np.array([[5, 6],  #square matrix 2x2
                [7, 8]])

print(M_1 + M_2)

[[ 6  8]
 [10 12]]


In [98]:
#PRODOTTO MATRICIALE

M_1 = np.array([[1, 2],  #square matrix 2x2
                [3, 4]])
      
M_2 = np.array([[5, 6],  #square matrix 2x2
                [7, 8]])

print(np.dot(M_1,M_2))   #OUTPUT : square matrix 2x2

[[19 22]
 [43 50]]


In [99]:
M_1= np.array([[1,2,3], #2x3
               [0,1,2]]) 

M_2= np.array([[4,5],   #3x2
               [6,7],
               [8,9]])

print(np.dot(M_1,M_2))  #OUTPUT square matrix: 2x2

[[40 46]
 [22 25]]


In [100]:
M_1 @ M_2 # @ -> another option

array([[40, 46],
       [22, 25]])

# System of linear equations

A system of linear equations (or linear system) is a collection of one or more linear equations involving the same set of variables.

<img src="https://miro.medium.com/max/1400/1*6LRv9DMK9hXvwm5JVpTQuA.png" alt="500" width="600" align="left"/>

In [101]:
#Abbiamo un chiosco allo stadio dove vendiamo:

#Hot dogs cost €1.50
#Coca Cola cost €0.50
#Made a total of €78.50
#Sold 87 hot dogs and Coca Cola combined

#How many Hot Dogs(x) and Coca Cola(y) have been sold?

In [102]:
# 1.50x + 0.50y = 78.50  (Equation related to cost)

# x + y = 87   (Equation related to the number sold)

In [103]:
a= np.array([[1.50, 0.5], #MATRICE COEFFICIENTI
             [1, 1]])

b= np.array([[78.50], #MATRICE TERMINI NOTI
              [87]])

In [112]:
#Calculate inverse of A

inv_a= np.linalg.inv(a)

In [113]:
ID= a @ inv_a  #identity matrix
ID

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [114]:
ID_2= np.eye(2)
ID_2

array([[1., 0.],
       [0., 1.]])

In [115]:
np.allclose(ID, ID_2) #confrontiamo le 2 matrici identità solo per sicurezza.

True

In [117]:
X= inv_a @ b #matrice delle Soluzioni (valori incognite)
X

array([[35.],
       [52.]])

In [ ]:
print("Hello")

In [118]:
#Built in function -> linalg.solve() -> DIRETTAMENTE MATRICE SOLUZIONI

np.linalg.solve(a, b)

array([[35.],
       [52.]])

<img src="https://media.istockphoto.com/vectors/congratulations-greeting-sign-congrats-graduated-vector-id1148641884?k=20&m=1148641884&s=170667a&w=0&h=UZvEyiD5nxDJiLz5n0i1jdvWn-MR6wt1nomiPV1wSDE=" alt="400" width="500" align="left"/>